// <auto-generated />
namespace Lessons_Cordinator_v1._0.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class MIG2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(MIG2));
        
        string IMigrationMetadata.Id
        {
            get { return "202002290234363_MIG2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
